# Project information
site_name: Dice
site_description: A Material Design theme for MkDocs
site_author: Jonah Snider
site_url: https://dice.js.org

# Repository
repo_name: dice-discord/docs
repo_url: https://github.com/dice-discord/docs

# Copyright
copyright: Copyright 2020 <a href="https://jonah.pw">Jonah Snider</a>

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  palette:
    scheme: slate
    primary: green
    accent: green
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: casino
    cta: fontawesome/brands/discord
    repo: fontawesome/brands/github
  features:
    - tabs
    - instant

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dice-discord
    - icon: fontawesome/brands/discord
      link: https://dice.js.org/server
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/pizzafox
    - icon: fontawesome/solid/plus
      link: https://dice.js.org/invite
  manifest: manifest.webmanifest
  docs_repo_url: https://github.com/dice-discord/bot
  features:
    tabs: true
  # Call to action button in the upper right of the page
  cta_text: Connect to Discord
  cta_url: https://dice.js.org/invite

plugins:
  - search:
      prebuild_index: true
  # - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true

# Google Analytics
google_analytics:
  - UA-133415948-1
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
